#!/usr/bin/env python3

# Created by: Mr. Coxall
# Created on: Sep 2019
# This program draws a background on the PyBadge

import ugame
import stage

# an image bank for CircuitPython
image_bank_1 = stage.Bank.from_bmp16("ball.bmp")

def main():
# This is what fills in the background
    background = stage.Grid(image_bank_1, 10, 8)
# This is what displays the ball
    background.tile(4, 3, 3)

    game = stage.Stage(ugame.display, 60)
    game.layers = [background]
    game.render_block()

# This makes it cycle
    while True:
        pass


if __name__ == "__main__":
    main()
